// Code generated by mdatagen. DO NOT EDIT.

package ztracereceiver

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestComponentLifecycle(t *testing.T) {
	factory := NewFactory()
	tests := []struct {
		name     string
		createFn func(ctx componenttest.TestContext) (component.Component, error)
	}{
		{
			name: "metrics",
			createFn: func(ctx componenttest.TestContext) (component.Component, error) {
				cfg := factory.CreateDefaultConfig()
				return factory.CreateMetrics(ctx, ctx.Setting, cfg, ctx.Sink)
			},
		},
		{
			name: "traces",
			createFn: func(ctx componenttest.TestContext) (component.Component, error) {
				cfg := factory.CreateDefaultConfig()
				return factory.CreateTraces(ctx, ctx.Setting, cfg, ctx.Sink)
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c, err := test.createFn(componenttest.TestContext{})
			require.NoError(t, err)
			componenttest.CheckComponentLifecycle(t, c)
		})
	}
}