// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetIperfTargetHost sets provided value as "iperf.target.host" attribute.
func (rb *ResourceBuilder) SetIperfTargetHost(val string) {
	if rb.config.IperfTargetHost.Enabled {
		rb.res.Attributes().PutStr("iperf.target.host", val)
	}
}

// SetIperfTargetPort sets provided value as "iperf.target.port" attribute.
func (rb *ResourceBuilder) SetIperfTargetPort(val int64) {
	if rb.config.IperfTargetPort.Enabled {
		rb.res.Attributes().PutInt("iperf.target.port", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
