// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for iperf metrics.
type MetricsConfig struct {
	IperfBandwidth      MetricConfig `mapstructure:"iperf.bandwidth"`
	IperfCPUUtilization MetricConfig `mapstructure:"iperf.cpu.utilization"`
	IperfCwnd           MetricConfig `mapstructure:"iperf.cwnd"`
	IperfJitter         MetricConfig `mapstructure:"iperf.jitter"`
	IperfPacketLoss     MetricConfig `mapstructure:"iperf.packet_loss"`
	IperfRetransmits    MetricConfig `mapstructure:"iperf.retransmits"`
	IperfRtt            MetricConfig `mapstructure:"iperf.rtt"`
	IperfTestDuration   MetricConfig `mapstructure:"iperf.test.duration"`
	IperfTestError      MetricConfig `mapstructure:"iperf.test.error"`
	IperfTransfer       MetricConfig `mapstructure:"iperf.transfer"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		IperfBandwidth: MetricConfig{
			Enabled: true,
		},
		IperfCPUUtilization: MetricConfig{
			Enabled: false,
		},
		IperfCwnd: MetricConfig{
			Enabled: false,
		},
		IperfJitter: MetricConfig{
			Enabled: true,
		},
		IperfPacketLoss: MetricConfig{
			Enabled: true,
		},
		IperfRetransmits: MetricConfig{
			Enabled: true,
		},
		IperfRtt: MetricConfig{
			Enabled: false,
		},
		IperfTestDuration: MetricConfig{
			Enabled: true,
		},
		IperfTestError: MetricConfig{
			Enabled: true,
		},
		IperfTransfer: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for iperf resource attributes.
type ResourceAttributesConfig struct {
	IperfTargetHost ResourceAttributeConfig `mapstructure:"iperf.target.host"`
	IperfTargetPort ResourceAttributeConfig `mapstructure:"iperf.target.port"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		IperfTargetHost: ResourceAttributeConfig{
			Enabled: true,
		},
		IperfTargetPort: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for iperf metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
