// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					IperfBandwidth:      MetricConfig{Enabled: true},
					IperfCPUUtilization: MetricConfig{Enabled: true},
					IperfCwnd:           MetricConfig{Enabled: true},
					IperfJitter:         MetricConfig{Enabled: true},
					IperfPacketLoss:     MetricConfig{Enabled: true},
					IperfRetransmits:    MetricConfig{Enabled: true},
					IperfRtt:            MetricConfig{Enabled: true},
					IperfTestDuration:   MetricConfig{Enabled: true},
					IperfTestError:      MetricConfig{Enabled: true},
					IperfTransfer:       MetricConfig{Enabled: true},
				},
				ResourceAttributes: ResourceAttributesConfig{
					IperfTargetHost: ResourceAttributeConfig{Enabled: true},
					IperfTargetPort: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					IperfBandwidth:      MetricConfig{Enabled: false},
					IperfCPUUtilization: MetricConfig{Enabled: false},
					IperfCwnd:           MetricConfig{Enabled: false},
					IperfJitter:         MetricConfig{Enabled: false},
					IperfPacketLoss:     MetricConfig{Enabled: false},
					IperfRetransmits:    MetricConfig{Enabled: false},
					IperfRtt:            MetricConfig{Enabled: false},
					IperfTestDuration:   MetricConfig{Enabled: false},
					IperfTestError:      MetricConfig{Enabled: false},
					IperfTransfer:       MetricConfig{Enabled: false},
				},
				ResourceAttributes: ResourceAttributesConfig{
					IperfTargetHost: ResourceAttributeConfig{Enabled: false},
					IperfTargetPort: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				IperfTargetHost: ResourceAttributeConfig{Enabled: true},
				IperfTargetPort: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				IperfTargetHost: ResourceAttributeConfig{Enabled: false},
				IperfTargetPort: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
